version: "2"
services:
  websocketd:
    environment:
      - APP_DIR /opt/app
      - ENV CSHARP $APP_DIR/program
      - ENV DOTNET_CLI_TELEMETRY_OPTOUT 1
    build: MyApp
    container_name: MyApp
    restart: always
    volumes:
      - ./MyApp/app/program:/opt/app/program/
    ports:
      - "80:80"
